services:
  aplication:
    container_name: appNode
    restart: always
    build: .
    ports:
      - "4040:3000"
    links:
      - databaseMongo
    volumes:
      - .:/mnt/Nas/Programacion/Sori/The Bridge/ejercicios-online/Sprint 23/appnode
  databaseMongo:
    container_name: mongoDB
    image: mongo
    ports:
      - "27017:27017"